server:
  port: ${SERVER_PORT:8090}
  shutdown: ${SERVER_SHUTDOWN:graceful}
  undertow:
    threads:
      io: ${UNDERTOW_IO_THREADS:10}
      worker: ${UNDERTOW_IO_WORKERS:100}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:mc-orders}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mcorders}
    username: ${USERNAME_DATABASE:mcorders}
    password: ${PASSWORD_PASSWORD:mcorders}
  jpa:
    generate-ddl: ${SPRING_JPA_GENERATE_DDL:false}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    properties:
      hibernate:
        show_sql: ${SPRING_JPA_PROPERTIES_SHOW_SQL:false}
        format_sql: ${SPRING_JPA_PROPERTIES_FORMAT_SQL:false}
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW:false}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
    org.hibernate.type.descriptor.sql: ${LOGGING_LEVEL:INFO}
  pattern:
    console: "[%thread][%highlight(%-5level)][%cyan(%d{yyyy-MM-dd HH:mm:ss})][%yellow(%X{requestId})][%magenta(%logger{40})] - %msg%n"